name: Build Executable

on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build executable
      run: pyinstaller --onefile your_script.py
    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: your_app
        path: dist/your_script.exe
